Add Android.mk for building hdcp service on Android
intel/hdcp pull request #7
Opened 2018-09-26 08:58 UTC by kromli

Add Android Makefile to build hdcp on Android. With this Android.mk
this module can be built either using mm, mma or make from Android root
directory.

To make specific module, the module name is specified in each of the added
Android.mk

REVERTME: Revert this if upstream (VPG's github) acceptted same patch.

Change-Id: Ib1de06c25a5fb8da95f92bef53dbc292042c7ac8
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-68872
Signed-off-by: khairul.anuar.romli@intel.com

2018-09-27 19:53 UTC, bpscully requested changes

2018-09-27 19:53 UTC, bpscully commented on daemon/main.cpp
> +    const std::string pidFile = "/data/hdcp/hdcpd.pid";
Could you please #define a constant string which changes for Android instead of using an #ifdef in the code?

2018-09-28 03:10 UTC, kromli commented
I have define the constant as being suggested.

2018-09-28 16:58 UTC, bpscully approved these changes

2018-10-08 07:13 UTC, XiangKaren approved these changes

2018-10-08 07:17 UTC, shiqiangyu approved these changes

2018-11-07 02:50 UTC, shiqiangyu commented
Already merged

2018-11-07 02:50 UTC, closed without merging